name: 20 - Deploy & Run (DAB)

on:
  workflow_dispatch:
    inputs:
      cluster_spark_version:
        description: "DBR LTS (ex.: 14.3.x-scala2.12)"
        required: false
        default: "14.3.x-scala2.12"
      node_type_id:
        description: "SKU (ex.: Standard_DS3_v2)"
        required: false
        default: "Standard_F4"
  workflow_run:
    workflows: ["10 - Upload arquivo para RAW"]
    types: [completed]

permissions:
  contents: read
  id-token: write

jobs:
  deploy_and_run:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      # ---- Preencha estas variáveis / secrets no repositório de DADOS ----
      # Recomendado: adicionar output na infra com o resource_id da workspace.
      BUNDLE_VAR_azure_workspace_resource_id: ${{ secrets.AZURE_DATABRICKS_WORKSPACE_RESOURCE_ID }}

      # Autenticação SPN bootstrap (mesma usada no azure/login)
      BUNDLE_VAR_azure_client_id:  ${{ secrets.ARM_CLIENT_ID }}
      BUNDLE_VAR_azure_tenant_id:  ${{ secrets.ARM_TENANT_ID }}

      # SPN dinâmica (client_id) recuperada do Key Vault pela infra;
      # se preferir, busque no KV também aqui (como no infra). Para simplificar, coloque como secret.
      BUNDLE_VAR_dynamic_spn_client_id: ${{ secrets.DYNAMIC_SPN_CLIENT_ID }}

      # Cluster params (podem vir dos inputs)
      BUNDLE_VAR_cluster_spark_version: ${{ github.event.inputs.cluster_spark_version || '14.3.x-scala2.12' }}
      BUNDLE_VAR_node_type_id:          ${{ github.event.inputs.node_type_id || 'Standard_DS3_v2' }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (SPN bootstrap)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Databricks CLI (bundles)
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks -v

      # Opcional: validar sintaxe/config antes do deploy
      - name: DAB validate
        run: databricks bundle validate -t dev

      - name: DAB deploy
        run: databricks bundle deploy -t dev

      - name: DAB run job
        run: databricks bundle run -t dev ingest_bronze --no-ui
